name: Fatkhur-server2

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
    - name: download assets files.
      run: |
        Invoke-WebRequest https://oss.asklink.com/updata/official-version/windows/AskLink-Installer-v3.6.2.10-x64-20241205-1603.exe -OutFile AskLink-Installer.exe
        Invoke-WebRequest https://raw.githubusercontent.com/rqx110/windowsrdp/main/loop.bat -OutFile loop.bat
        Invoke-WebRequest https://raw.githubusercontent.com/rqx110/windowsrdp/main/start.bat -OutFile start.bat
    - name: install AskLink.
      run: .\AskLink-Installer.exe /VERYSILENT
    - name: run AskLink.
      run: '"C:\Program Files\AskLink\AskLink.exe"'
    - name: Sleep for 20s
      uses: juliangruber/sleep-action@v2.0.0
      with:
        time: 20s
    - name: Set Password
      run: '"C:\Program Files\AskLink\AskLinkCommand.exe" --set-password P12345'
    - name: Get ID
      run: '"C:\Program Files\AskLink\AskLinkCommand.exe" --get-id'
    - name: Connect Ke RDP Kamu CPU 2 Core - 7GB Ram - 255 SSD.
      run: cmd /c start.bat
    - name: RDP Berhasil Dibuat Nung!! 
      run: cmd /c loop.bat
