name: Fatkhur-server2

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
    - name: download assets files.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/rqx110/windowsrdp/main/ToDesk.zip -OutFile todesk.zip
        Invoke-WebRequest https://raw.githubusercontent.com/rqx110/windowsrdp/main/loop.bat -OutFile loop.bat
        Invoke-WebRequest https://raw.githubusercontent.com/rqx110/windowsrdp/main/start.bat -OutFile start.bat
    
    - name: extract todesk file.
      run: Expand-Archive todesk.zip
    - name: run todesk.
      run: .\todesk\ToDesk\ToDesk.exe
    - name: Sleep for 10s
      uses: juliangruber/sleep-action@v2.0.0
      with:
        time: 10s
    - name: connect todesk.
      run: |
        Get-Content todesk\ToDesk\config.ini -totalcount 2
    - name: Connect Ke RDP Kamu CPU 2 Core - 7GB Ram - 255 SSD.
      run: cmd /c start.bat
    - name: RDP Berhasil Dibuat Nung!! 
      run: cmd /c loop.bat
